### ISSUE TITLE
[Release]: 0.1.0

### ISSUE THREAD

**Issue by vitalics** [vitalics/playwright-prometheus-remote-write-reporter#14]
This meta issue describes progress to next release (0.1.0).

Checkbox enabled - finished features(done). 

## Feature
- [x] custom env support: #13 and #8 

- [x] custom labels: #10, #9, #11, 

## Bug fixes

- [x] auth is not applies #15  

## infra
- [x] migrate to pnpm instead of bun due to `node:` prefix usage #12

**Comment by xTrekStorex** [comment]
might want to add #15 to this release

**Comment by vitalics** [comment]
shipped 🚀!
